# See https://github.com/googleapis/repo-automation-bots/tree/main/packages/blunderbuss

assign_issues:
  - alexander-fenster
  - bcoe
  - sofisl
  - summer-ji-eng

assign_prs:
  - alexander-fenster
  - bcoe
  - sofisl
  - summer-ji-eng
